history reset

diff --git a/scripts/.githooks/pre-commit b/scripts/.githooks/pre-commit
--- a/scripts/.githooks/pre-commit
+++ b/scripts/.githooks/pre-commit
@@ -12,26 +12,29 @@ if [[ "$STAGED_GO_FILES" = "" ]]; then
   exit 0
 fi
 
+# can not check only changed files as if it references structs etc in same package
+# but in different file it reports that as 'route.go:18:11: undefined: Service'
+go vet ./...
+if [[ $? != 0 ]]; then
+  printf "go vet FAILED\n"
+  exit 1
+fi
+
 PASS=true
 
-for FILE in $STAGED_GO_FILES
+for FILE in ${STAGED_GO_FILES}
 do
   if [[ ! -f ${FILE} ]]; then
     continue
   fi
 
-  go tool vet $FILE
-  if [[ $? != 0 ]]; then
-    PASS=false
-  fi
-
-  golint -set_exit_status $FILE
+  golint -set_exit_status ${FILE}
   if [[ $? != 0 ]]; then
     PASS=false
   fi
 done
 
-if ! $PASS; then
+if ! ${PASS}; then
   printf "COMMIT FAILED\n"
   exit 1
 else
